version: '3.9'
services:
  api:
    container_name: 'api'
    build: ./api
    ports:
      - 8000:80
    volumes:
      - ./api/app:/code
  
  bot:
    container_name: 'telegram_bot'
    build: ./bot
    ports:
      - 6000:6000
    volumes:
      - ./bot:/app
  

  db:
    container_name: 'db'
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}