version: '3.9'
services:
  api:
    container_name: 'api'
    build: ./api
    ports:
      - 8000:80
    volumes:
      - ./api/app:/code
  
  bot:
    container_name: 'telegram_bot'
    build: ./bot
    ports:
      - 6000:6000
    volumes:
      - ./bot:/app
  

  db:
    container_name: 'db'
    image: mysql:8
    ports:
      - "3310:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}